services:
  backend:
    build:
      context: backend/.
    ports:
      - 8000:8000
  frontend:
    build:
      context: frontend/.
    ports:
      - 5173:5173


  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "tasks12345"
      POSTGRES_DB: "postgres"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432